routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/client', function () {
	\Illuminate\Support\Facades\Auth::loginUsingId(2);
});

Route::get('/', function () {
	return view('welcome');
});

Route::get('/app', function () {
	return view('layouts.spa');
});

Route::get('/home', function () {
	return redirect()->route('admin.home');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function(){

	// Authentication Routes...
	Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
	Route::post('login', 'Auth\LoginController@login');
	Route::post('logout', 'Auth\LoginController@logout')->name('logout');
	// Registration Routes...
	Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
	Route::post('register', 'Auth\RegisterController@register');
	// Password Reset Routes...
	Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
	Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
	Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
	Route::post('password/reset', 'Auth\ResetPasswordController@reset');

	Route::group(['middleware' => 'can:access-admin'], function(){
		Route::get('/home', 'HomeController@index')->name('home');
		Route::resource('banks', 'Admin\BanksController', ['except' => 'show']);
	});
});

Route::group(['prefix' => '/', 'as' => 'site.'], function(){
	Route::get('/', function(){
		return view('site.home');
	})->name('home');

	Route::get('register', 'Site\Auth\RegisterController@create')->name('auth.register.create');
	Route::post('register', 'Site\Auth\RegisterController@store')->name('auth.register.store');

	Route::group(['prefix' => 'subscriptions', 'as' => 'subscriptions.'], function(){
		Route::get('successfully', 'Site\SubscriptionsController@successfully')->name('successfully');
		Route::get('create', 'Site\SubscriptionsController@create')->name('create');
		Route::post('store', 'Site\SubscriptionsController@store')->name('store');
	});

	Route::group(['prefix' => 'my-financial', 'as' => 'my-financial' ,'middleware' => 'auth.from_token'], function(){
		Route::get('/', function(){
			echo 'teste';
		});
	});

	Route::get('login', 'Site\Auth\LoginController@showLoginForm')->name('auth.login.login');
	Route::post('login', 'Site\Auth\LoginController@login');
	Route::post('logout', 'Site\Auth\LoginController@logout');

});

app/Models/Bank.php
<?php

namespace Finapp\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Bank extends Model implements Transformable
{
	use TransformableTrait;

	protected $fillable = [
		'name',
		'logo'
	];

	public static function logosDir(){
		return 'banks/images';
	}

	public function getLogoPathAttribute(){
		return "storage/banks/images/$this->logo";
	}
}

app/Http/Controllers/Admin/BanksController.php
<?php

namespace Finapp\Http\Controllers\Admin;

use Finapp\Http\Controllers\Controller;
use Finapp\Http\Controllers\Response;

use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use Finapp\Http\Requests\BankCreateRequest;
use Finapp\Http\Requests\BankUpdateRequest;
use Finapp\Repositories\BankRepository;


class BanksController extends Controller{

	/**
	 * @var BankRepository
	 */
	protected $repository;

	protected $validator;

	public function __construct(BankRepository $repository){
		$this->repository = $repository;
		$this->repository->skipPresenter(true);
		//$this->validator  = $validator;
	}


	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index(){
		$banks = $this->repository->paginate(5);

		/*if (request()->wantsJson()) {
			return response()->json([
				'data' => $banks,
			]);
		}*/

		return view('admin.banks.index', compact('banks'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  BankCreateRequest $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store(BankCreateRequest $request){
		$data = $request->all();
		$this->repository->create($data);

		/*if ($request->wantsJson()) {
			$response = [
				'message' => 'Bank created.',
				'data'    => $bank->toArray(),
			];

			return response()->json($response);
		}*/

		return redirect()->route('admin.banks.index');
	}

	public function create(){
		return view('admin.banks.create');
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id){
		$bank = $this->repository->find($id);

		return view('admin.banks.edit', compact('bank'));
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  BankUpdateRequest $request
	 * @param  string            $id
	 *
	 * @return Response
	 */
	public function update(BankUpdateRequest $request, $id){
		$this->repository->update($request->all(), $id);

		/* if ($request->wantsJson()) {
			$response = [
				'message' => 'Bank updated.',
				'data'    => $bank->toArray(),
			];
			return response()->json($response);
		} */

		return redirect()->route('admin.banks.index');
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id){
		$deleted = $this->repository->delete($id);

		/*if (request()->wantsJson()) {

			return response()->json([
				'message' => 'Bank deleted.',
				'deleted' => $deleted,
			]);
		}*/

		return redirect()->back()->with('message', 'Bank deleted.');
	}
}

app/Http/Controllers/Api/BanksController.php
<?php

namespace Finapp\Http\Controllers\Api;

use Finapp\Repositories\BankRepository;
use Finapp\Http\Controllers\Controller;

class BanksController extends Controller{
	/*
	 * @var BankRepositorye
	 */
	private $repositorie;

	function __construct(BankRepository $repositorie){
		$this->repositorie = $repositorie;
	}

	public function index(){
		return $this->repositorie->all();
	}
}

resources/views/admin/banks/_form.blade.php
<div class="row">
	<div class="row">
		<div class="input-field col s6">
			<?php $errorClass = $errors->first('name')? ['class' => 'validade invalid'] : []; ?>
			{!! Form::text('name', null, $errorClass) !!}
			{!! Form::label('name', 'Nome', ['data-error' => $errors->first('name')]) !!}
		</div> 
	</div>
	<div class="row">
		<div class="input-field file-field col s6">
			<div class="btn">
				<span>Logo</span>
				{!! Form::file('logo') !!}
			</div>
			<div class="file-path-wrapper">
				<input type="text" class="file-path">
			</div>
		</div>
	</div>

	<div class="row">
		<div class="input-field col s12">
			{!! Form::submit('Enviar', ['class' => 'btn waves-effect right']) !!}
		</div>
	</div>
</div>

resources/views/admin/banks/create.blade.php
@extends('layouts.admin')

@section('content')

	<div class="container">
		<div class="row">
			<h4>Novo Banco</h4>
			{!! Form::open(['route' => 'admin.banks.store', 'files' => true]) !!}

			@include('admin.banks._form')

			{!! Form::close() !!}
		</div>
	</div>

@endsection

resources/views/admin/banks/edit.blade.php
@extends('layouts.admin')

@section('content')

	<div class="container">
		<div class="row">
			<h4>Editar Banco</h4>
			{!! 
				Form::model(
					$bank, 
					[
						'route' => ['admin.banks.update', 'bank' => $bank->id],
						'method' => 'PUT',
						'files' => true
					]
				) 
			!!}

			@include('admin.banks._form')

			{!! Form::close() !!}
		</div>
	</div>

@endsection

resources/views/admin/banks/index.blade.php
@extends('layouts.admin')

@section('content')
	<div class="container">
		<div class="row">
			<h4>Listagem de Bancos</h4>
			<a href="{{ route('admin.banks.create') }}" class="btn waves-effect">Novo Banco</a>
			<table class="bordered striped highlight centered responsive-table z-depth-5">
				<thead>
					<tr>
						<th>#</th>
						<th>Nome</th>
						<th>Ações</th>
					</tr>
				</thead>
				<tbody>
					@foreach($banks as $bank)
						<tr>
							<td>
								<div class="row valign-wrapper">
									<div class="col s12">{{ $bank->id }}</div>
								</div>
							</td>
							<td>
								<div class="row valign-wrapper">
									<div class="col s2">
										<img src="{{asset($bank->logoPath)}}" class="bank-logo">
									</div>
									<div class="col s10">
										<span class="left">{{ $bank->name }}</span>
									</div>
								</div>
							</td>
							<td>
								<div class="row valign-wrapper">
									<div class="col s12">
										<a href="{{ route('admin.banks.edit', ['bank' => $bank->id]) }}">Editar</a> | 
										<delete-action action="{{ route('admin.banks.destroy', ['bank' => $bank->id]) }}" 
														action-element="link-delete-{{$bank->id}}" csrf-token="{{ csrf_token() }}">
											<?php $modalId = "modal-delete-{$bank->id}"; ?>
											<a id="link-modal-{{$bank->id}}" href="#{{ $modalId }}">Excluir</a>
											<modal :modal="{{json_encode(['id' => $modalId])}}" style="display: none;">
												<div slot="content">
													<div slot="content">
														<h5>Mensagem de confirmação</h5>
														<p>Deseja excluir este banco?</p>
														<div class="divider"></div>
														<p>Nome: <strong>{{ $bank->name }}</strong></p>
														<div class="divider"></div>
													</div>
													<div slot="footer" class="right">
														<br>
														<button class="btn btn-flat waves-effect waves-red modal-action modal-close">Cancelar</button>
														<button class="btn btn-flat waves-effect green lighten-2 modal-action modal-close" id="link-delete-{{$bank->id}}">OK</button>
													</div>
												</div>
											</modal>
										</delete-action>
									</div>
								</div>
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
			{!! $banks->links() !!}
		</div>
	</div>

@endsection