routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/client', function () {
	\Illuminate\Support\Facades\Auth::loginUsingId(2);
});

Route::get('/', function () {
	return view('welcome');
});

Route::get('/app', function () {
	return view('layouts.spa');
});

Route::get('/home', function () {
	return redirect()->route('admin.home');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function(){

	// Authentication Routes...
	Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
	Route::post('login', 'Auth\LoginController@login');
	Route::post('logout', 'Auth\LoginController@logout')->name('logout');
	// Registration Routes...
	Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
	Route::post('register', 'Auth\RegisterController@register');
	// Password Reset Routes...
	Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
	Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
	Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
	Route::post('password/reset', 'Auth\ResetPasswordController@reset');

	Route::group(['middleware' => 'can:access-admin'], function(){
		Route::get('/home', 'HomeController@index')->name('home');
		Route::resource('banks', 'Admin\BanksController', ['except' => 'show']);
	});
});

Route::group(['prefix' => '/', 'as' => 'site.'], function(){
	Route::get('/', function(){
		return view('site.home');
	})->name('home');

	Route::get('register', 'Site\Auth\RegisterController@create')->name('auth.register.create');
	Route::post('register', 'Site\Auth\RegisterController@store')->name('auth.register.store');

	Route::group(['prefix' => 'subscriptions', 'as' => 'subscriptions.'], function(){
		Route::get('successfully', 'Site\SubscriptionsController@successfully')->name('successfully');
		Route::get('create', 'Site\SubscriptionsController@create')->name('create');
		Route::post('store', 'Site\SubscriptionsController@store')->name('store');
	});

	Route::group(['prefix' => 'my-financial', 'as' => 'my-financial' ,'middleware' => 'auth.from_token'], function(){
		Route::get('/', function(){
			echo 'teste';
		});
	});

	Route::get('login', 'Site\Auth\LoginController@showLoginForm')->name('auth.login.login');
	Route::post('login', 'Site\Auth\LoginController@login');
	Route::post('logout', 'Site\Auth\LoginController@logout');

});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- CSRF Token -->
	<meta name="csrf-token" content="{{ csrf_token() }}">

	<title>{{ config('app.name', 'Laravel') }}</title>

	<!-- Styles -->
	<link href="{{ asset('css/admin.css') }}" rel="stylesheet">
</head>
<body>
	<div id="app">
		<header>
			@if (Auth::check())
				<admin-menu :config="menus"></admin-menu>
			@endif
		</header>
		<main>
			@yield('content')
		</main>
		<footer class="page-footer">
			<div class="footer-copyright">
				<div class="container">
					© {{ date('Y') }} <a href="http://fb.com/maiglon" class="grey-text text-lighten-4">Maiglon Lubacheuski</a>
				</div>
			</div>
		</footer>
	</div>

	<!-- Scripts -->
	<script src="{{ asset('build/admin.bundle.js') }}"></script>
	@if (Auth::check())
		<script type="text/javascript">
			const app = new Vue({
				el: '#app',
				data: {
					menus: {
						'name': "{{ Auth::user()->name }}",
						'menus': [
							{'name': 'teste', 'url': '/home', 'dropdownId': 'teste'},
							{
								'name': 'Bancos', 
								'url': '{{ route('admin.banks.index') }}',
								'active': {{ isRouteActive('admin.banks.index') }}
							}
						],
						'menusDropdown': [
							{
								'id': 'teste',
								'items': [
									{'name': 'Listar contas', 'url': '/listar'},
									{
										'name': 'Bancos', 
										'url': '{{ route('admin.banks.index') }}',
										'active': {{ isRouteActive('admin.banks.index') }}
									}
								]
							}
						],
						'urlLogout': "{{ route('admin.logout') }}",
						'csrfToken': "{{ csrf_token() }}"
					}
				}
			});
		</script>
	@endif

</body>
</html>

resources/views/layouts/site.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- CSRF Token -->
		<meta name="csrf-token" content="{{ csrf_token() }}">

		<title>{{ config('app.name', 'Finapp') }}</title>

		<!-- Styles -->
		<link href="{{ asset('css/site.css') }}" rel="stylesheet">
	</head>
	<body>
		<div id="app">
			<header>
				<?php
					$menuConfig = [
						'auth' => (boolean)Auth::check(),
						'name' => Auth::check() ? Auth::user()->name : '',
						'menus' => [
							[
								'name' => "Home",
								'url' => url('/'),
								'active' => isRouteActive('site.home')
							]
						],
						'menusDropDown' => [],
						'urlLogout' => env('URL_SITE_LOGOUT'),
						'csrfToken' => csrf_token()
					];
				?>
				<site-menu :config="{{ json_encode($menuConfig) }}"></site-menu>
			</header>
			<main>
				@yield('content')
			</main>
			<footer class="page-footer">
				<div class="footer-copyright">
					<div class="container">
						© {{ date('') }} <a href="http://maiglon.com" class="gre-text text-lighten-4">Maiglon Lubacheuski</a>
					</div>
				</div>
			</footer>
		</div>
		<!-- Scripts -->
		@stack('scripts')
		<script src="{{ asset('build/site.bundle.js') }}"></script>
	</body>
</html>

resources/views/layouts/spa.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- CSRF Token -->
	<meta name="csrf-token" content="{{ csrf_token() }}">

	<title>{{ config('app.name', 'Finapp') }}</title>

	<!-- Styles -->
	<link href="{{ asset('css/spa.css') }}" rel="stylesheet">
</head>
<body>
	<div id="spaApp">
		<app></app>
	</div>
	<!-- Scripts -->
	<script src="{{ asset('build/spa.bundle.js') }}"></script>
</body>
</html>